/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pertemuan5;

/**
 *
 * @author yusuf-laptop
 */
public class TiketMaskapai extends javax.swing.JFrame {

    /**
     * Creates new form TiketMaskapai
     */
    public TiketMaskapai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        cb_jurusan = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cb_maskapai = new javax.swing.JComboBox<>();
        txt_harga = new javax.swing.JTextField();
        txt_jumlah = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_notif = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cb_jurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "= Pilih =", "Yogyakarta", "Semarang" }));
        cb_jurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_jurusanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tiket Pesawat");

        cb_maskapai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "= Pilih =", "Garuda Indonesia", "Citilink", "Air Asia" }));
        cb_maskapai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_maskapaiActionPerformed(evt);
            }
        });

        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Jurusan");

        jLabel3.setText("Maskapai");

        jLabel4.setText("Harga");

        jLabel5.setText("Jumlah Tiket");

        jLabel6.setText("Total Harga");

        lbl_notif.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_notif.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_notif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_jurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_maskapai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_harga)
                            .addComponent(txt_jumlah)
                            .addComponent(txt_total))))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_maskapai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(lbl_notif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void cb_maskapaiActionPerformed(java.awt.event.ActionEvent evt) {                                            
        int jurusan;
        int maskapai;
        int  harga;
        String nama;
        jurusan = cb_jurusan.getSelectedIndex();
        maskapai = cb_maskapai.getSelectedIndex();
        switch (maskapai){
            case 1:
                if (jurusan==1){
                   harga =55000; 
                   nama ="Garuda Indonesia - Yogyakarta";
                }
                else if (jurusan==2){
                   harga =520000; 
                   nama ="Garuda Indonesia - Semarang";
                }
                else {
                   harga =0; 
                   nama ="-";
                }
                break;
            case 2:
                if (jurusan==1){
                   harga =440000; 
                   nama ="Citilink - Yogyakarta";
                }
                else if (jurusan==2){
                   harga =420000; 
                   nama ="Citilink - Semarang";
                }
                else {
                   harga =0; 
                   nama ="-";
                }
                break;
            case 3:
                if (jurusan==1){
                   harga =330000; 
                   nama ="Air Asia - Yogyakarta";
                }
                else if (jurusan==2){
                   harga =320000; 
                   nama ="Air Asia - Semarang";
                }
                else {
                   harga =0; 
                   nama ="-";
                }
                break;
            default :
                harga =0;
                nama ="";
        }
        txt_harga.setText(Integer.toString(harga));
        lbl_notif.setText(nama);
    }                                           

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int a=Integer.parseInt(txt_harga.getText());
        int b=Integer.parseInt(txt_jumlah.getText());
        int e=a*b;
        txt_total.setText(Integer.toString(e));
    }                                        

    private void cb_jurusanActionPerformed(java.awt.event.ActionEvent evt) {                                           
        int jurusan;
        int maskapai;
        int  harga;
        String nama;
        jurusan = cb_jurusan.getSelectedIndex();
        maskapai = cb_maskapai.getSelectedIndex();
        switch (jurusan){
            case 1:
                if (maskapai==1){
                   harga   =550000;
                    nama    ="Garuda Indonesia - Yogyakarta";
                }
                else if (maskapai==2){
                   harga =440000; 
                   nama ="Citilink - Yogyakarta";
                }
                else if (maskapai==3){
                   harga =330000; 
                   nama ="Air Asia - Yogyakarta";
                }
                else {
                   harga =0; 
                   nama ="-";
                }
                break;
            case 2:
                if (maskapai==1){
                   harga   =520000;
                    nama    ="Garuda Indonesia - Semarang";
                }
                else if (maskapai==2){
                   harga =420000; 
                   nama ="Citilink - Semarang";
                }
                else if (maskapai==3){
                   harga =320000; 
                   nama ="Air Asia - Semarang";
                }
                else {
                   harga =0; 
                   nama ="";
                }
                break;
            default :
                harga   =0;
                nama    ="";
        }
        txt_harga.setText(Integer.toString(harga));
        lbl_notif.setText(nama);
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiketMaskapai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiketMaskapai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiketMaskapai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiketMaskapai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiketMaskapai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> cb_jurusan;
    private javax.swing.JComboBox<String> cb_maskapai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_notif;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_total;
    // End of variables declaration                   
}
