/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Quiz_NIM;

import javax.swing.JOptionPane;

/**
 *
 * @author yusuf-laptop
 */
public class Quiz_Type_B extends javax.swing.JFrame {

    /**
     * Creates new form Quiz_Type_B
     */
    public Quiz_Type_B() {
        initComponents();
        txt_uang_kembali.setEditable(false);
        txt_nama_kamar.setEditable(false);
        txt_harga.setEditable(false);
        txt_sarapan.setEditable(false);
        txt_total.setEditable(false);
        txt_nama_tamu.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nama_tamu = new javax.swing.JTextField();
        txt_nama_kamar = new javax.swing.JTextField();
        cb_kode_kamar = new javax.swing.JComboBox<>();
        txt_harga = new javax.swing.JTextField();
        txt_lama_inap = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        txt_bayar = new javax.swing.JTextField();
        txt_uang_kembali = new javax.swing.JTextField();
        btn_hitung = new javax.swing.JButton();
        btn_bersih = new javax.swing.JButton();
        btn_tutup = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        radio_sarapan = new javax.swing.JRadioButton();
        txt_tanpa_sarapan = new javax.swing.JRadioButton();
        txt_sarapan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quiz_13180486_Type_B");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Hotel Liburan Asik");

        jLabel2.setText("Nama Tamu");

        jLabel3.setText("Kode Kamar");

        jLabel4.setText("Nama Kamar");

        jLabel5.setText("Harga Kamar");

        jLabel6.setText("Lama Inap");

        txt_nama_kamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nama_kamarActionPerformed(evt);
            }
        });

        cb_kode_kamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Kode-", "A001", "M002", "T003" }));
        cb_kode_kamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_kode_kamarActionPerformed(evt);
            }
        });

        txt_harga.setText("0");

        txt_lama_inap.setText("0");
        txt_lama_inap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lama_inapActionPerformed(evt);
            }
        });
        txt_lama_inap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_lama_inapKeyPressed(evt);
            }
        });

        jLabel7.setText("Total Bayar");

        txt_total.setText("0");

        txt_bayar.setText("0");
        txt_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bayarActionPerformed(evt);
            }
        });

        txt_uang_kembali.setText("0");

        btn_hitung.setText("Hitung");
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });

        btn_bersih.setText("Bersih");
        btn_bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bersihActionPerformed(evt);
            }
        });

        btn_tutup.setText("Tutup");
        btn_tutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tutupActionPerformed(evt);
            }
        });

        jLabel8.setText("Uang Bayar");

        jLabel9.setText("Uang Kembali");

        buttonGroup1.add(radio_sarapan);
        radio_sarapan.setText("Sarapan");
        radio_sarapan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio_sarapanItemStateChanged(evt);
            }
        });
        radio_sarapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_sarapanActionPerformed(evt);
            }
        });

        buttonGroup1.add(txt_tanpa_sarapan);
        txt_tanpa_sarapan.setText("Tanpa Sarapan");
        txt_tanpa_sarapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tanpa_sarapanActionPerformed(evt);
            }
        });

        txt_sarapan.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_sarapan)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radio_sarapan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_tanpa_sarapan)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_sarapan)
                    .addComponent(txt_tanpa_sarapan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(txt_sarapan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_lama_inap)
                            .addComponent(txt_harga)
                            .addComponent(txt_nama_kamar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_uang_kembali)
                            .addComponent(txt_bayar)
                            .addComponent(txt_total, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_nama_tamu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_kode_kamar, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btn_hitung)
                .addGap(47, 47, 47)
                .addComponent(btn_bersih)
                .addGap(37, 37, 37)
                .addComponent(btn_tutup)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_nama_tamu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cb_kode_kamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_nama_kamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_lama_inap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_hitung)
                            .addComponent(btn_bersih)
                            .addComponent(btn_tutup)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_uang_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void txt_nama_kamarActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void btn_tutupActionPerformed(java.awt.event.ActionEvent evt) {                                          
        System.exit(0);
    }                                         

    private void cb_kode_kamarActionPerformed(java.awt.event.ActionEvent evt) {                                              
        String kode_kamar;
        String nama_kamar;
        int harga;
        int pilih_cb_kode_kamar;
        pilih_cb_kode_kamar = cb_kode_kamar.getSelectedIndex();
        switch (pilih_cb_kode_kamar){
            case 0:
                kode_kamar ="0";
                harga =0;
                nama_kamar ="";
                break;
            case 1:
                kode_kamar ="A001";
                harga =1000000;
                nama_kamar ="Anggrek";
                break;
            case 2:
                kode_kamar ="M002";
                harga =750000;
                nama_kamar ="Mawar";
                break;
            case 3:
                kode_kamar ="T003";
                harga =500000;
                nama_kamar ="Tulip";
                break;                
            default :
                kode_kamar ="0";
                harga =0;
                nama_kamar ="";
        }
        txt_harga.setText(Integer.toString(harga));
        txt_nama_kamar.setText(nama_kamar);
        txt_lama_inap.requestFocus();
    }                                             

    private void radio_sarapanItemStateChanged(java.awt.event.ItemEvent evt) {                                               
        txt_sarapan.setText(Integer.toString(100000));
    }                                              

    private void txt_lama_inapKeyPressed(java.awt.event.KeyEvent evt) {                                         

        // TODO add your handling code here:
    }                                        

    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {                                           
        fungsi_hitung_total();
    }                                          

    private void txt_bayarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        int a=Integer.parseInt(txt_total.getText());
        int b=Integer.parseInt(txt_bayar.getText());
        int kembali=b-a;
        txt_uang_kembali.setText(Integer.toString(kembali));
        if (kembali<0){
            JOptionPane.showMessageDialog(null, "Uang bayar kurang");
        }
    }                                         

    private void btn_bersihActionPerformed(java.awt.event.ActionEvent evt) {                                           
        txt_nama_tamu.setText("");
        txt_total.setText("0");
        txt_bayar.setText("0");
        txt_uang_kembali.setText("0");
        txt_harga.setText("0");
        txt_lama_inap.setText("0");
        txt_sarapan.setText("0");
        cb_kode_kamar.setSelectedIndex(0);
        txt_nama_tamu.requestFocus();
    }                                          

    private void txt_lama_inapActionPerformed(java.awt.event.ActionEvent evt) {                                              
        fungsi_hitung_total();
    }                                             

    private void radio_sarapanActionPerformed(java.awt.event.ActionEvent evt) {                                              
        if (radio_sarapan.isSelected()){
            txt_sarapan.setText(Integer.toString(100000));
            cb_kode_kamar.requestFocus();
        }
    }                                             

    private void txt_tanpa_sarapanActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        if (txt_tanpa_sarapan.isSelected()){
            txt_sarapan.setText(Integer.toString(0));
            cb_kode_kamar.requestFocus();
        }        // TODO add your handling code here:
    }                                                 
 
    private void fungsi_hitung_total(){
        int pilih_cb_kode_kamar;
        pilih_cb_kode_kamar = cb_kode_kamar.getSelectedIndex();
        if (pilih_cb_kode_kamar==0){
            JOptionPane.showMessageDialog(null, "Kode kamar belum di pilih");
            cb_kode_kamar.requestFocus();
        } else {
            int z=Integer.parseInt(txt_lama_inap.getText());
            if (z<1){
                JOptionPane.showMessageDialog(null, "Lama inap minimal 1 hari");
                txt_lama_inap.requestFocus();
            } else {
                int a=Integer.parseInt(txt_harga.getText());
                int b=Integer.parseInt(txt_lama_inap.getText());
                int c=Integer.parseInt(txt_sarapan.getText());
                int total=(a*b)+c;
                txt_total.setText(Integer.toString(total));
                txt_bayar.requestFocus();
            }
        }
    }

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz_Type_B.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz_Type_B.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz_Type_B.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz_Type_B.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz_Type_B().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify                     
    private javax.swing.JButton btn_bersih;
    private javax.swing.JButton btn_hitung;
    private javax.swing.JButton btn_tutup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_kode_kamar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radio_sarapan;
    private javax.swing.JTextField txt_bayar;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_lama_inap;
    private javax.swing.JTextField txt_nama_kamar;
    private javax.swing.JTextField txt_nama_tamu;
    private javax.swing.JTextField txt_sarapan;
    private javax.swing.JRadioButton txt_tanpa_sarapan;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_uang_kembali;
    // End of variables declaration                   
}
